version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8010:8010"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    environment:
      - VITE_API_BASE_URL=http://backend:8010/api/v1
    ports:
      - "5002:5002"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: manutencao_dashboard_net
    driver: bridge